mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "create database ${MYSQL_PRISMA_SHADOW_DATABASE};"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '$MYSQL_USER'@'%'; FLUSH PRIVILEGES"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${MYSQL_PRISMA_SHADOW_DATABASE}.* TO '$MYSQL_USER'@'%'; FLUSH PRIVILEGES"